// Code generated by "stringer -type Cmd"; DO NOT EDIT.

package queuedproto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CmdAddItem-20]
	_ = x[CmdGetActive-21]
	_ = x[CmdDeleteItems-22]
	_ = x[CmdUpdateItems-24]
	_ = x[CmdGetItems-28]
	_ = x[CmdFullUpdate-30]
	_ = x[CmdAddData-34]
	_ = x[CmdGetQueueStat-36]
}

const (
	_Cmd_name_0 = "CmdAddItemCmdGetActiveCmdDeleteItems"
	_Cmd_name_1 = "CmdUpdateItems"
	_Cmd_name_2 = "CmdGetItems"
	_Cmd_name_3 = "CmdFullUpdate"
	_Cmd_name_4 = "CmdAddData"
	_Cmd_name_5 = "CmdGetQueueStat"
)

var (
	_Cmd_index_0 = [...]uint8{0, 10, 22, 36}
)

func (i Cmd) String() string {
	switch {
	case 20 <= i && i <= 22:
		i -= 20
		return _Cmd_name_0[_Cmd_index_0[i]:_Cmd_index_0[i+1]]
	case i == 24:
		return _Cmd_name_1
	case i == 28:
		return _Cmd_name_2
	case i == 30:
		return _Cmd_name_3
	case i == 34:
		return _Cmd_name_4
	case i == 36:
		return _Cmd_name_5
	default:
		return "Cmd(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
