// Code generated by iprotogen. DO NOT EDIT.

package queuedproto

import (
	"encoding/binary"
	"fmt"

	iproto "github.com/my-mail-ru/go-iproto"
)

func (recvPerlAddons PerlAddons) MarshalIProto(buf []byte) ([]byte, error) {
	if len(recvPerlAddons.List) > 255 {
		return nil, fmt.Errorf("MarshalIProto: Len(recvPerlAddons.List): %w: %d > %d", iproto.ErrOverflow, len(recvPerlAddons.List), 255)
	}
	buf = append(buf, byte(len(recvPerlAddons.List)))
	for _, elemRecvPerlAddons_List := range recvPerlAddons.List {
		buf = append(buf, byte(elemRecvPerlAddons_List.ID), byte(elemRecvPerlAddons_List.ID>>8))
		if len(elemRecvPerlAddons_List.Data) > 255 {
			return nil, fmt.Errorf("MarshalIProto: Len(elemRecvPerlAddons_List.Data): %w: %d > %d", iproto.ErrOverflow, len(elemRecvPerlAddons_List.Data), 255)
		}
		buf = append(buf, byte(len(elemRecvPerlAddons_List.Data)))
		buf = append(buf, elemRecvPerlAddons_List.Data...)
	}
	return buf, nil
}
func (recv_PerlAddons *PerlAddons) UnmarshalIProto(buf []byte) ([]byte, error) {
	if len(buf) < 1 {
		return nil, fmt.Errorf("UnmarshalIProto: LenRecv_PerlAddons_List: %w: %d < %d", iproto.ErrOverflow, len(buf), 1)
	}
	lenRecv_PerlAddons_List := int(buf[0])
	buf = buf[1:]
	if len(buf) < lenRecv_PerlAddons_List {
		return nil, fmt.Errorf("UnmarshalIProto: Recv_PerlAddons.List: %w: %d < %d", iproto.ErrOverflow, len(buf), lenRecv_PerlAddons_List)
	}
	recv_PerlAddons.List = make([]PerlAddonData, lenRecv_PerlAddons_List)
	for iRecv_PerlAddons_List := 0; iRecv_PerlAddons_List < lenRecv_PerlAddons_List; iRecv_PerlAddons_List++ {
		if len(buf) < 2 {
			return nil, fmt.Errorf("UnmarshalIProto: Recv_PerlAddons.List[iRecv_PerlAddons_List].ID: %w: %d < %d", iproto.ErrOverflow, len(buf), 2)
		}
		recv_PerlAddons.List[iRecv_PerlAddons_List].ID = binary.LittleEndian.Uint16(buf)
		buf = buf[2:]
		if len(buf) < 1 {
			return nil, fmt.Errorf("UnmarshalIProto: LenRecv_PerlAddons_List_iRecv_PerlAddons_List__Data: %w: %d < %d", iproto.ErrOverflow, len(buf), 1)
		}
		lenRecv_PerlAddons_List_iRecv_PerlAddons_List__Data := int(buf[0])
		buf = buf[1:]
		if len(buf) < lenRecv_PerlAddons_List_iRecv_PerlAddons_List__Data {
			return nil, fmt.Errorf("UnmarshalIProto: Recv_PerlAddons.List[iRecv_PerlAddons_List].Data: %w: %d < %d", iproto.ErrOverflow, len(buf), lenRecv_PerlAddons_List_iRecv_PerlAddons_List__Data)
		}
		recv_PerlAddons.List[iRecv_PerlAddons_List].Data = append([]byte{}, buf[:lenRecv_PerlAddons_List_iRecv_PerlAddons_List__Data]...)
		buf = buf[lenRecv_PerlAddons_List_iRecv_PerlAddons_List__Data:]
	}
	return buf, nil
}
func (recvPerlExtensions PerlExtensions) MarshalIProto(buf []byte) ([]byte, error) {
	buf = append(buf, byte(recvPerlExtensions.Flags), byte(recvPerlExtensions.Flags>>8), byte(recvPerlExtensions.Flags>>16), byte(recvPerlExtensions.Flags>>24))
	buf = append(buf, byte(len(recvPerlExtensions.Data)), byte(len(recvPerlExtensions.Data)>>8), byte(len(recvPerlExtensions.Data)>>16), byte(len(recvPerlExtensions.Data)>>24))
	buf = append(buf, recvPerlExtensions.Data...)
	return buf, nil
}
func (recv_PerlExtensions *PerlExtensions) UnmarshalIProto(buf []byte) ([]byte, error) {
	if len(buf) < 4 {
		return nil, fmt.Errorf("UnmarshalIProto: Recv_PerlExtensions.Flags: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	recv_PerlExtensions.Flags = binary.LittleEndian.Uint32(buf)
	buf = buf[4:]
	if len(buf) < 4 {
		return nil, fmt.Errorf("UnmarshalIProto: LenRecv_PerlExtensions_Data: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	lenRecv_PerlExtensions_Data := int(binary.LittleEndian.Uint32(buf))
	buf = buf[4:]
	if len(buf) < lenRecv_PerlExtensions_Data {
		return nil, fmt.Errorf("UnmarshalIProto: Recv_PerlExtensions.Data: %w: %d < %d", iproto.ErrOverflow, len(buf), lenRecv_PerlExtensions_Data)
	}
	recv_PerlExtensions.Data = append([]byte{}, buf[:lenRecv_PerlExtensions_Data]...)
	buf = buf[lenRecv_PerlExtensions_Data:]
	return buf, nil
}
