// Code generated by iprotogen. DO NOT EDIT.

package queuedproto

import (
	"encoding/binary"
	"fmt"

	iproto "github.com/my-mail-ru/go-iproto"
)

func (recvTestPerlData testPerlData) MarshalIProto(buf []byte) ([]byte, error) {
	buf = append(buf, byte(recvTestPerlData.ID), byte(recvTestPerlData.ID>>8), byte(recvTestPerlData.ID>>16), byte(recvTestPerlData.ID>>24))
	buf = append(buf, byte(recvTestPerlData.Value), byte(recvTestPerlData.Value>>8), byte(recvTestPerlData.Value>>16), byte(recvTestPerlData.Value>>24))
	return buf, nil
}
func (recv_testPerlData *testPerlData) UnmarshalIProto(buf []byte) ([]byte, error) {
	if len(buf) < 4 {
		return nil, fmt.Errorf("UnmarshalIProto: Recv_testPerlData.ID: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	recv_testPerlData.ID = binary.LittleEndian.Uint32(buf)
	buf = buf[4:]
	if len(buf) < 4 {
		return nil, fmt.Errorf("UnmarshalIProto: Recv_testPerlData.Value: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	recv_testPerlData.Value = binary.LittleEndian.Uint32(buf)
	buf = buf[4:]
	return buf, nil
}
