// Code generated by iprotogen. DO NOT EDIT.

package queuedproto

import (
	"encoding/binary"
	"fmt"

	iproto "github.com/my-mail-ru/go-iproto"
)

func (recvEventID EventID) MarshalIProto(buf []byte) ([]byte, error) {
	buf = append(buf, byte(recvEventID.ID), byte(recvEventID.ID>>8), byte(recvEventID.ID>>16), byte(recvEventID.ID>>24), byte(recvEventID.ID>>32), byte(recvEventID.ID>>40), byte(recvEventID.ID>>48), byte(recvEventID.ID>>56))
	return buf, nil
}
func (recv_EventID *EventID) UnmarshalIProto(buf []byte) ([]byte, error) {
	if len(buf) < 8 {
		return nil, fmt.Errorf("UnmarshalIProto: Recv_EventID.ID: %w: %d < %d", iproto.ErrOverflow, len(buf), 8)
	}
	recv_EventID.ID = binary.LittleEndian.Uint64(buf)
	buf = buf[8:]
	return buf, nil
}
func (recvItemList ItemList) MarshalIProto(buf []byte) ([]byte, error) {
	buf = append(buf, byte(len(recvItemList.Items)), byte(len(recvItemList.Items)>>8), byte(len(recvItemList.Items)>>16), byte(len(recvItemList.Items)>>24))
	for _, elemRecvItemList_Items := range recvItemList.Items {
		buf = append(buf, byte(elemRecvItemList_Items.EventID.ID), byte(elemRecvItemList_Items.EventID.ID>>8), byte(elemRecvItemList_Items.EventID.ID>>16), byte(elemRecvItemList_Items.EventID.ID>>24), byte(elemRecvItemList_Items.EventID.ID>>32), byte(elemRecvItemList_Items.EventID.ID>>40), byte(elemRecvItemList_Items.EventID.ID>>48), byte(elemRecvItemList_Items.EventID.ID>>56))
		if len(elemRecvItemList_Items.Data) > 65535 {
			return nil, fmt.Errorf("MarshalIProto: Len(elemRecvItemList_Items.Data): %w: %d > %d", iproto.ErrOverflow, len(elemRecvItemList_Items.Data), 65535)
		}
		buf = append(buf, byte(len(elemRecvItemList_Items.Data)), byte(len(elemRecvItemList_Items.Data)>>8))
		buf = append(buf, elemRecvItemList_Items.Data...)
	}
	return buf, nil
}
func (recv_ItemList *ItemList) UnmarshalIProto(buf []byte) ([]byte, error) {
	if len(buf) < 4 {
		return nil, fmt.Errorf("UnmarshalIProto: LenRecv_ItemList_Items: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	lenRecv_ItemList_Items := int(binary.LittleEndian.Uint32(buf))
	buf = buf[4:]
	if len(buf) < lenRecv_ItemList_Items {
		return nil, fmt.Errorf("UnmarshalIProto: Recv_ItemList.Items: %w: %d < %d", iproto.ErrOverflow, len(buf), lenRecv_ItemList_Items)
	}
	recv_ItemList.Items = make([]QueueItem, lenRecv_ItemList_Items)
	for iRecv_ItemList_Items := 0; iRecv_ItemList_Items < lenRecv_ItemList_Items; iRecv_ItemList_Items++ {
		if len(buf) < 8 {
			return nil, fmt.Errorf("UnmarshalIProto: Recv_ItemList.Items[iRecv_ItemList_Items].EventID.ID: %w: %d < %d", iproto.ErrOverflow, len(buf), 8)
		}
		recv_ItemList.Items[iRecv_ItemList_Items].EventID.ID = binary.LittleEndian.Uint64(buf)
		buf = buf[8:]
		if len(buf) < 2 {
			return nil, fmt.Errorf("UnmarshalIProto: LenRecv_ItemList_Items_iRecv_ItemList_Items__Data: %w: %d < %d", iproto.ErrOverflow, len(buf), 2)
		}
		lenRecv_ItemList_Items_iRecv_ItemList_Items__Data := int(binary.LittleEndian.Uint16(buf))
		buf = buf[2:]
		if len(buf) < lenRecv_ItemList_Items_iRecv_ItemList_Items__Data {
			return nil, fmt.Errorf("UnmarshalIProto: Recv_ItemList.Items[iRecv_ItemList_Items].Data: %w: %d < %d", iproto.ErrOverflow, len(buf), lenRecv_ItemList_Items_iRecv_ItemList_Items__Data)
		}
		recv_ItemList.Items[iRecv_ItemList_Items].Data = append([]byte{}, buf[:lenRecv_ItemList_Items_iRecv_ItemList_Items__Data]...)
		buf = buf[lenRecv_ItemList_Items_iRecv_ItemList_Items__Data:]
	}
	return buf, nil
}
