// Code generated by iprotogen. DO NOT EDIT.
package queuedproto

import (
	"encoding/binary"
	"fmt"

	iproto "github.com/my-mail-ru/go-iproto"
)

func (recvReqQueueStat ReqQueueStat) MarshalIProto(buf []byte) ([]byte, error) {
	buf = append(buf, recvReqQueueStat.Version)
	buf = append(buf, byte(recvReqQueueStat.StorageType), byte(recvReqQueueStat.StorageType>>8))
	return buf, nil
}
func (recv_ReqQueueStat *ReqQueueStat) UnmarshalIProto(buf []byte) ([]byte, error) {
	if len(buf) < 1 {
		return nil, fmt.Errorf("MarshalIProto: Recv_ReqQueueStat.Version: %w: %d < %d", iproto.ErrOverflow, len(buf), 1)
	}
	recv_ReqQueueStat.Version = buf[0]
	buf = buf[1:]
	if len(buf) < 2 {
		return nil, fmt.Errorf("MarshalIProto: Recv_ReqQueueStat.StorageType: %w: %d < %d", iproto.ErrOverflow, len(buf), 2)
	}
	recv_ReqQueueStat.StorageType = binary.LittleEndian.Uint16(buf)
	buf = buf[2:]
	return buf, nil
}
func (recvRespQueueStat RespQueueStat) MarshalIProto(buf []byte) ([]byte, error) {
	buf = append(buf, byte(recvRespQueueStat.ItemsCount), byte(recvRespQueueStat.ItemsCount>>8), byte(recvRespQueueStat.ItemsCount>>16), byte(recvRespQueueStat.ItemsCount>>24))
	buf = append(buf, byte(recvRespQueueStat.ActiveCount), byte(recvRespQueueStat.ActiveCount>>8), byte(recvRespQueueStat.ActiveCount>>16), byte(recvRespQueueStat.ActiveCount>>24))
	buf = append(buf, byte(recvRespQueueStat.LockedCount), byte(recvRespQueueStat.LockedCount>>8), byte(recvRespQueueStat.LockedCount>>16), byte(recvRespQueueStat.LockedCount>>24))
	return buf, nil
}
func (recv_RespQueueStat *RespQueueStat) UnmarshalIProto(buf []byte) ([]byte, error) {
	if len(buf) < 4 {
		return nil, fmt.Errorf("MarshalIProto: Recv_RespQueueStat.ItemsCount: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	recv_RespQueueStat.ItemsCount = binary.LittleEndian.Uint32(buf)
	buf = buf[4:]
	if len(buf) < 4 {
		return nil, fmt.Errorf("MarshalIProto: Recv_RespQueueStat.ActiveCount: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	recv_RespQueueStat.ActiveCount = binary.LittleEndian.Uint32(buf)
	buf = buf[4:]
	if len(buf) < 4 {
		return nil, fmt.Errorf("MarshalIProto: Recv_RespQueueStat.LockedCount: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	recv_RespQueueStat.LockedCount = binary.LittleEndian.Uint32(buf)
	buf = buf[4:]
	return buf, nil
}
