// Code generated by iprotogen. DO NOT EDIT.

package queuedproto

import (
	"encoding/binary"
	"fmt"

	iproto "github.com/my-mail-ru/go-iproto"
)

func (recvReqDeleteItems ReqDeleteItems) MarshalIProto(buf []byte) ([]byte, error) {
	buf = append(buf, byte(recvReqDeleteItems.StorageType), byte(recvReqDeleteItems.StorageType>>8))
	buf = append(buf, byte(len(recvReqDeleteItems.IDs)), byte(len(recvReqDeleteItems.IDs)>>8), byte(len(recvReqDeleteItems.IDs)>>16), byte(len(recvReqDeleteItems.IDs)>>24))
	for _, elemRecvReqDeleteItems_IDs := range recvReqDeleteItems.IDs {
		buf = append(buf, byte(elemRecvReqDeleteItems_IDs), byte(elemRecvReqDeleteItems_IDs>>8), byte(elemRecvReqDeleteItems_IDs>>16), byte(elemRecvReqDeleteItems_IDs>>24), byte(elemRecvReqDeleteItems_IDs>>32), byte(elemRecvReqDeleteItems_IDs>>40), byte(elemRecvReqDeleteItems_IDs>>48), byte(elemRecvReqDeleteItems_IDs>>56))
	}
	return buf, nil
}
func (recv_ReqDeleteItems *ReqDeleteItems) UnmarshalIProto(buf []byte) ([]byte, error) {
	if len(buf) < 2 {
		return nil, fmt.Errorf("UnmarshalIProto: Recv_ReqDeleteItems.StorageType: %w: %d < %d", iproto.ErrOverflow, len(buf), 2)
	}
	recv_ReqDeleteItems.StorageType = binary.LittleEndian.Uint16(buf)
	buf = buf[2:]
	if len(buf) < 4 {
		return nil, fmt.Errorf("UnmarshalIProto: LenRecv_ReqDeleteItems_IDs: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	lenRecv_ReqDeleteItems_IDs := int(binary.LittleEndian.Uint32(buf))
	buf = buf[4:]
	if len(buf) < lenRecv_ReqDeleteItems_IDs {
		return nil, fmt.Errorf("UnmarshalIProto: Recv_ReqDeleteItems.IDs: %w: %d < %d", iproto.ErrOverflow, len(buf), lenRecv_ReqDeleteItems_IDs)
	}
	recv_ReqDeleteItems.IDs = make([]uint64, lenRecv_ReqDeleteItems_IDs)
	for iRecv_ReqDeleteItems_IDs := 0; iRecv_ReqDeleteItems_IDs < lenRecv_ReqDeleteItems_IDs; iRecv_ReqDeleteItems_IDs++ {
		if len(buf) < 8 {
			return nil, fmt.Errorf("UnmarshalIProto: Recv_ReqDeleteItems.IDs[iRecv_ReqDeleteItems_IDs]: %w: %d < %d", iproto.ErrOverflow, len(buf), 8)
		}
		recv_ReqDeleteItems.IDs[iRecv_ReqDeleteItems_IDs] = binary.LittleEndian.Uint64(buf)
		buf = buf[8:]
	}
	return buf, nil
}
