// Code generated by iprotogen. DO NOT EDIT.
package queuedproto

import (
	"encoding/binary"
	"fmt"
	"slices"

	iproto "github.com/my-mail-ru/go-iproto"
)

func (recvReqAddData ReqAddData) MarshalIProto(buf []byte) ([]byte, error) {
	buf = append(buf, byte(recvReqAddData.StorageType), byte(recvReqAddData.StorageType>>8))
	buf = append(buf, byte(recvReqAddData.ID), byte(recvReqAddData.ID>>8), byte(recvReqAddData.ID>>16), byte(recvReqAddData.ID>>24), byte(recvReqAddData.ID>>32), byte(recvReqAddData.ID>>40), byte(recvReqAddData.ID>>48), byte(recvReqAddData.ID>>56))
	if len(recvReqAddData.Data) > 65535 {
		return nil, fmt.Errorf("MarshalIProto: Len(recvReqAddData.Data): %w: %d > %d", iproto.ErrOverflow, len(recvReqAddData.Data), 65535)
	}
	buf = append(buf, byte(len(recvReqAddData.Data)), byte(len(recvReqAddData.Data)>>8))
	buf = append(buf, recvReqAddData.Data...)
	return buf, nil
}
func (recv_ReqAddData *ReqAddData) UnmarshalIProto(buf []byte) ([]byte, error) {
	if len(buf) < 2 {
		return nil, fmt.Errorf("MarshalIProto: Recv_ReqAddData.StorageType: %w: %d < %d", iproto.ErrOverflow, len(buf), 2)
	}
	recv_ReqAddData.StorageType = binary.LittleEndian.Uint16(buf)
	buf = buf[2:]
	if len(buf) < 8 {
		return nil, fmt.Errorf("MarshalIProto: Recv_ReqAddData.ID: %w: %d < %d", iproto.ErrOverflow, len(buf), 8)
	}
	recv_ReqAddData.ID = binary.LittleEndian.Uint64(buf)
	buf = buf[8:]
	if len(buf) < 2 {
		return nil, fmt.Errorf("MarshalIProto: LenRecv_ReqAddData_Data: %w: %d < %d", iproto.ErrOverflow, len(buf), 2)
	}
	lenRecv_ReqAddData_Data := int(binary.LittleEndian.Uint16(buf))
	buf = buf[2:]
	if len(buf) < lenRecv_ReqAddData_Data {
		return nil, fmt.Errorf("MarshalIProto: Recv_ReqAddData.Data: %w: %d < %d", iproto.ErrOverflow, len(buf), lenRecv_ReqAddData_Data)
	}
	recv_ReqAddData.Data = slices.Clone(buf[:lenRecv_ReqAddData_Data])
	buf = buf[lenRecv_ReqAddData_Data:]
	return buf, nil
}
