// Code generated by iprotogen. DO NOT EDIT.
package queuedproto

import (
	"encoding/binary"
	"fmt"
	"slices"

	iproto "github.com/my-mail-ru/go-iproto"
)

func (recvReqAddItemDumb reqAddItemDumb) MarshalIProto(buf []byte) ([]byte, error) {
	buf = append(buf, byte(recvReqAddItemDumb.Pid), byte(recvReqAddItemDumb.Pid>>8), byte(recvReqAddItemDumb.Pid>>16), byte(recvReqAddItemDumb.Pid>>24))
	buf = append(buf, byte(recvReqAddItemDumb.ReqID), byte(recvReqAddItemDumb.ReqID>>8), byte(recvReqAddItemDumb.ReqID>>16), byte(recvReqAddItemDumb.ReqID>>24))
	buf = append(buf, byte(recvReqAddItemDumb.StorageType), byte(recvReqAddItemDumb.StorageType>>8))
	buf = append(buf, byte(recvReqAddItemDumb.ID), byte(recvReqAddItemDumb.ID>>8), byte(recvReqAddItemDumb.ID>>16), byte(recvReqAddItemDumb.ID>>24), byte(recvReqAddItemDumb.ID>>32), byte(recvReqAddItemDumb.ID>>40), byte(recvReqAddItemDumb.ID>>48), byte(recvReqAddItemDumb.ID>>56))
	buf = append(buf, byte(recvReqAddItemDumb.UnixTime), byte(recvReqAddItemDumb.UnixTime>>8), byte(recvReqAddItemDumb.UnixTime>>16), byte(recvReqAddItemDumb.UnixTime>>24))
	if len(recvReqAddItemDumb.Data) > 65535 {
		return nil, fmt.Errorf("MarshalIProto: Len(recvReqAddItemDumb.Data): %w: %d > %d", iproto.ErrOverflow, len(recvReqAddItemDumb.Data), 65535)
	}
	buf = append(buf, byte(len(recvReqAddItemDumb.Data)), byte(len(recvReqAddItemDumb.Data)>>8))
	buf = append(buf, recvReqAddItemDumb.Data...)
	return buf, nil
}
func (recv_reqAddItemDumb *reqAddItemDumb) UnmarshalIProto(buf []byte) ([]byte, error) {
	if len(buf) < 4 {
		return nil, fmt.Errorf("MarshalIProto: Recv_reqAddItemDumb.Pid: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	recv_reqAddItemDumb.Pid = binary.LittleEndian.Uint32(buf)
	buf = buf[4:]
	if len(buf) < 4 {
		return nil, fmt.Errorf("MarshalIProto: Recv_reqAddItemDumb.ReqID: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	recv_reqAddItemDumb.ReqID = binary.LittleEndian.Uint32(buf)
	buf = buf[4:]
	if len(buf) < 2 {
		return nil, fmt.Errorf("MarshalIProto: Recv_reqAddItemDumb.StorageType: %w: %d < %d", iproto.ErrOverflow, len(buf), 2)
	}
	recv_reqAddItemDumb.StorageType = binary.LittleEndian.Uint16(buf)
	buf = buf[2:]
	if len(buf) < 8 {
		return nil, fmt.Errorf("MarshalIProto: Recv_reqAddItemDumb.ID: %w: %d < %d", iproto.ErrOverflow, len(buf), 8)
	}
	recv_reqAddItemDumb.ID = binary.LittleEndian.Uint64(buf)
	buf = buf[8:]
	if len(buf) < 4 {
		return nil, fmt.Errorf("MarshalIProto: Recv_reqAddItemDumb.UnixTime: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	recv_reqAddItemDumb.UnixTime = binary.LittleEndian.Uint32(buf)
	buf = buf[4:]
	if len(buf) < 2 {
		return nil, fmt.Errorf("MarshalIProto: LenRecv_reqAddItemDumb_Data: %w: %d < %d", iproto.ErrOverflow, len(buf), 2)
	}
	lenRecv_reqAddItemDumb_Data := int(binary.LittleEndian.Uint16(buf))
	buf = buf[2:]
	if len(buf) < lenRecv_reqAddItemDumb_Data {
		return nil, fmt.Errorf("MarshalIProto: Recv_reqAddItemDumb.Data: %w: %d < %d", iproto.ErrOverflow, len(buf), lenRecv_reqAddItemDumb_Data)
	}
	recv_reqAddItemDumb.Data = slices.Clone(buf[:lenRecv_reqAddItemDumb_Data])
	buf = buf[lenRecv_reqAddItemDumb_Data:]
	return buf, nil
}
