// Code generated by iprotogen. DO NOT EDIT.
package queuedproto

import (
	"encoding/binary"
	"fmt"

	iproto "github.com/my-mail-ru/go-iproto"
)

func (recvReqGetItems ReqGetItems) MarshalIProto(buf []byte) ([]byte, error) {
	buf = append(buf, byte(recvReqGetItems.StorageType), byte(recvReqGetItems.StorageType>>8))
	buf = append(buf, byte(len(recvReqGetItems.IDs)), byte(len(recvReqGetItems.IDs)>>8), byte(len(recvReqGetItems.IDs)>>16), byte(len(recvReqGetItems.IDs)>>24))
	for _, elemRecvReqGetItems_IDs := range recvReqGetItems.IDs {
		buf = append(buf, byte(elemRecvReqGetItems_IDs), byte(elemRecvReqGetItems_IDs>>8), byte(elemRecvReqGetItems_IDs>>16), byte(elemRecvReqGetItems_IDs>>24), byte(elemRecvReqGetItems_IDs>>32), byte(elemRecvReqGetItems_IDs>>40), byte(elemRecvReqGetItems_IDs>>48), byte(elemRecvReqGetItems_IDs>>56))
	}
	return buf, nil
}
func (recv_ReqGetItems *ReqGetItems) UnmarshalIProto(buf []byte) ([]byte, error) {
	if len(buf) < 2 {
		return nil, fmt.Errorf("MarshalIProto: Recv_ReqGetItems.StorageType: %w: %d < %d", iproto.ErrOverflow, len(buf), 2)
	}
	recv_ReqGetItems.StorageType = binary.LittleEndian.Uint16(buf)
	buf = buf[2:]
	if len(buf) < 4 {
		return nil, fmt.Errorf("MarshalIProto: LenRecv_ReqGetItems_IDs: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	lenRecv_ReqGetItems_IDs := int(binary.LittleEndian.Uint32(buf))
	buf = buf[4:]
	if len(buf) < lenRecv_ReqGetItems_IDs {
		return nil, fmt.Errorf("MarshalIProto: Recv_ReqGetItems.IDs: %w: %d < %d", iproto.ErrOverflow, len(buf), lenRecv_ReqGetItems_IDs)
	}
	recv_ReqGetItems.IDs = make([]uint64, lenRecv_ReqGetItems_IDs)
	for iRecv_ReqGetItems_IDs := 0; iRecv_ReqGetItems_IDs < lenRecv_ReqGetItems_IDs; iRecv_ReqGetItems_IDs++ {
		if len(buf) < 8 {
			return nil, fmt.Errorf("MarshalIProto: Recv_ReqGetItems.IDs[iRecv_ReqGetItems_IDs]: %w: %d < %d", iproto.ErrOverflow, len(buf), 8)
		}
		recv_ReqGetItems.IDs[iRecv_ReqGetItems_IDs] = binary.LittleEndian.Uint64(buf)
		buf = buf[8:]
	}
	return buf, nil
}
