// Code generated by iprotogen. DO NOT EDIT.

package queuedproto

import (
	"encoding/binary"
	"fmt"

	iproto "github.com/my-mail-ru/go-iproto"
)

func (recvReqUpdateItems ReqUpdateItems) MarshalIProto(buf []byte) ([]byte, error) {
	buf = append(buf, byte(recvReqUpdateItems.StorageType), byte(recvReqUpdateItems.StorageType>>8))
	buf = append(buf, byte(recvReqUpdateItems.UnixTime), byte(recvReqUpdateItems.UnixTime>>8), byte(recvReqUpdateItems.UnixTime>>16), byte(recvReqUpdateItems.UnixTime>>24))
	buf = append(buf, byte(len(recvReqUpdateItems.IDs)), byte(len(recvReqUpdateItems.IDs)>>8), byte(len(recvReqUpdateItems.IDs)>>16), byte(len(recvReqUpdateItems.IDs)>>24))
	for _, elemRecvReqUpdateItems_IDs := range recvReqUpdateItems.IDs {
		buf = append(buf, byte(elemRecvReqUpdateItems_IDs), byte(elemRecvReqUpdateItems_IDs>>8), byte(elemRecvReqUpdateItems_IDs>>16), byte(elemRecvReqUpdateItems_IDs>>24), byte(elemRecvReqUpdateItems_IDs>>32), byte(elemRecvReqUpdateItems_IDs>>40), byte(elemRecvReqUpdateItems_IDs>>48), byte(elemRecvReqUpdateItems_IDs>>56))
	}
	buf = append(buf, recvReqUpdateItems.TimestampType)
	return buf, nil
}
func (recv_ReqUpdateItems *ReqUpdateItems) UnmarshalIProto(buf []byte) ([]byte, error) {
	if len(buf) < 2 {
		return nil, fmt.Errorf("UnmarshalIProto: Recv_ReqUpdateItems.StorageType: %w: %d < %d", iproto.ErrOverflow, len(buf), 2)
	}
	recv_ReqUpdateItems.StorageType = binary.LittleEndian.Uint16(buf)
	buf = buf[2:]
	if len(buf) < 4 {
		return nil, fmt.Errorf("UnmarshalIProto: Recv_ReqUpdateItems.UnixTime: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	recv_ReqUpdateItems.UnixTime = binary.LittleEndian.Uint32(buf)
	buf = buf[4:]
	if len(buf) < 4 {
		return nil, fmt.Errorf("UnmarshalIProto: LenRecv_ReqUpdateItems_IDs: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	lenRecv_ReqUpdateItems_IDs := int(binary.LittleEndian.Uint32(buf))
	buf = buf[4:]
	if len(buf) < lenRecv_ReqUpdateItems_IDs {
		return nil, fmt.Errorf("UnmarshalIProto: Recv_ReqUpdateItems.IDs: %w: %d < %d", iproto.ErrOverflow, len(buf), lenRecv_ReqUpdateItems_IDs)
	}
	recv_ReqUpdateItems.IDs = make([]uint64, lenRecv_ReqUpdateItems_IDs)
	for iRecv_ReqUpdateItems_IDs := 0; iRecv_ReqUpdateItems_IDs < lenRecv_ReqUpdateItems_IDs; iRecv_ReqUpdateItems_IDs++ {
		if len(buf) < 8 {
			return nil, fmt.Errorf("UnmarshalIProto: Recv_ReqUpdateItems.IDs[iRecv_ReqUpdateItems_IDs]: %w: %d < %d", iproto.ErrOverflow, len(buf), 8)
		}
		recv_ReqUpdateItems.IDs[iRecv_ReqUpdateItems_IDs] = binary.LittleEndian.Uint64(buf)
		buf = buf[8:]
	}
	if len(buf) < 1 {
		return nil, fmt.Errorf("UnmarshalIProto: Recv_ReqUpdateItems.TimestampType: %w: %d < %d", iproto.ErrOverflow, len(buf), 1)
	}
	recv_ReqUpdateItems.TimestampType = buf[0]
	buf = buf[1:]
	return buf, nil
}
