// Code generated by iprotogen. DO NOT EDIT.
package queuedproto

import (
	"encoding/binary"
	"fmt"

	iproto "github.com/my-mail-ru/go-iproto"
)

func (recvReqFullUpdate ReqFullUpdate) MarshalIProto(buf []byte) ([]byte, error) {
	var err error
	buf = append(buf, byte(recvReqFullUpdate.StorageType), byte(recvReqFullUpdate.StorageType>>8))
	buf = append(buf, byte(recvReqFullUpdate.UnixTime), byte(recvReqFullUpdate.UnixTime>>8), byte(recvReqFullUpdate.UnixTime>>16), byte(recvReqFullUpdate.UnixTime>>24))
	buf = append(buf, byte(len(recvReqFullUpdate.Items)), byte(len(recvReqFullUpdate.Items)>>8), byte(len(recvReqFullUpdate.Items)>>16), byte(len(recvReqFullUpdate.Items)>>24))
	for _, elemRecvReqFullUpdate_Items := range recvReqFullUpdate.Items {
		buf, err = elemRecvReqFullUpdate_Items.MarshalIProto(buf)
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}
func (recv_ReqFullUpdate *ReqFullUpdate) UnmarshalIProto(buf []byte) ([]byte, error) {
	var err error
	if len(buf) < 2 {
		return nil, fmt.Errorf("MarshalIProto: Recv_ReqFullUpdate.StorageType: %w: %d < %d", iproto.ErrOverflow, len(buf), 2)
	}
	recv_ReqFullUpdate.StorageType = binary.LittleEndian.Uint16(buf)
	buf = buf[2:]
	if len(buf) < 4 {
		return nil, fmt.Errorf("MarshalIProto: Recv_ReqFullUpdate.UnixTime: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	recv_ReqFullUpdate.UnixTime = binary.LittleEndian.Uint32(buf)
	buf = buf[4:]
	if len(buf) < 4 {
		return nil, fmt.Errorf("MarshalIProto: LenRecv_ReqFullUpdate_Items: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	lenRecv_ReqFullUpdate_Items := int(binary.LittleEndian.Uint32(buf))
	buf = buf[4:]
	if len(buf) < lenRecv_ReqFullUpdate_Items {
		return nil, fmt.Errorf("MarshalIProto: Recv_ReqFullUpdate.Items: %w: %d < %d", iproto.ErrOverflow, len(buf), lenRecv_ReqFullUpdate_Items)
	}
	recv_ReqFullUpdate.Items = make([]UpdQueueItem, lenRecv_ReqFullUpdate_Items)
	for iRecv_ReqFullUpdate_Items := 0; iRecv_ReqFullUpdate_Items < lenRecv_ReqFullUpdate_Items; iRecv_ReqFullUpdate_Items++ {
		buf, err = recv_ReqFullUpdate.Items[iRecv_ReqFullUpdate_Items].UnmarshalIProto(buf)
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}
