// Code generated by iprotogen. DO NOT EDIT.

package queuedproto

import (
	"encoding/binary"
	"fmt"

	iproto "github.com/my-mail-ru/go-iproto"
)

func (recvReqGetActive ReqGetActive) MarshalIProto(buf []byte) ([]byte, error) {
	buf = append(buf, byte(recvReqGetActive.StorageType), byte(recvReqGetActive.StorageType>>8))
	buf = append(buf, byte(recvReqGetActive.Count), byte(recvReqGetActive.Count>>8), byte(recvReqGetActive.Count>>16), byte(recvReqGetActive.Count>>24))
	return buf, nil
}
func (recv_ReqGetActive *ReqGetActive) UnmarshalIProto(buf []byte) ([]byte, error) {
	if len(buf) < 2 {
		return nil, fmt.Errorf("UnmarshalIProto: Recv_ReqGetActive.StorageType: %w: %d < %d", iproto.ErrOverflow, len(buf), 2)
	}
	recv_ReqGetActive.StorageType = binary.LittleEndian.Uint16(buf)
	buf = buf[2:]
	if len(buf) < 4 {
		return nil, fmt.Errorf("UnmarshalIProto: Recv_ReqGetActive.Count: %w: %d < %d", iproto.ErrOverflow, len(buf), 4)
	}
	recv_ReqGetActive.Count = binary.LittleEndian.Uint32(buf)
	buf = buf[4:]
	return buf, nil
}
